"""update migration for tourmanagement

Revision ID: 14365369cb16
Revises: 5b5b14f03697
Create Date: 2025-12-01 17:49:36.458906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '14365369cb16'
down_revision: Union[str, None] = '5b5b14f03697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('participants_tour_id_fkey'), 'participants', type_='foreignkey')
    op.create_foreign_key(None, 'participants', 'tours', ['tour_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.create_foreign_key(op.f('participants_tour_id_fkey'), 'participants', 'tours', ['tour_id'], ['id'])
    # ### end Alembic commands ###
