"""make b-day and email nulluable true

Revision ID: 554da07a4887
Revises: a1b2c3d4e5f6
Create Date: 2026-05-14 14:04:26.633406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '554da07a4887'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('participants', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('participants', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
