"""remove fincode and document_seria

Revision ID: a1b2c3d4e5f6
Revises: 14365369cb16
Create Date: 2026-01-08 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '14365369cb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'fincode')
    op.drop_column('participants', 'document_seria')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('document_seria', sa.String(length=50), nullable=False))
    op.add_column('participants', sa.Column('fincode', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###
